### ISSUE TITLE
CSRF vulnerability

### ISSUE THREAD

**Issue by utiso** [vanderbilt-redcap/mysql-simple-admin#3]
A Cross-Site Request Forgery (CSRF) vulnerability permits attackers to take advantage of a legitimate user’s session to perform unauthorized actions on behalf of that user. Effectively, anything the given user has permissions to do,can be done without their knowledge by the attacker. These attacks can be very difficult to trace, as the activity appears to come from the authorized user.

This vulnerability is usually exploited with a specially crafted link that the user is asked to visit but, in conjunction with a persistent XSS vulnerability, it is possible to eliminate the need for a user to take any action.This attack is made possible because MySQL Simple Admin does not verify the origin and authenticity of requests before processing them. All pages that process requests that update data are vulnerable.

MySQL Simple Admin currently ignores REDCap's CSRF protection token, `redcap_csrf_token`. 

Submitting a POST to `/ExternalModules/?prefix=mysql_simple_admin&page=index` with the following values results in a response showing the contents of the auth table:
```
Upgrade-Insecure-Requests: 1

-----------------------------37166120963254603381588180274
Content-Disposition: form-data; name="query"

select * from redcap_auth
-----------------------------37166120963254603381588180274
Content-Disposition: form-data; name="redcap_csrf_token"

ignored
-----------------------------37166120963254603381588180274--
```

If combined with a Cross-Site Scripting vulnerability, data extraction from this module would be extremely simple.

**Comment by taylorr4** [comment]
@utiso Just an FYI, all REDCap external modules lack CSRF protection. It is not a built-in thing, plus i'm not aware of other module creators building their own module-level CSRF protection. So this is not surprising at all; it is a known thing. However, our team has begun prioritizing adding CSRF protection natively to the REDCap External Module Framework so that all modules can utilize it in the near future. So for this module, we'll wait until that feature has been added to the framework and add CSRF protection for it then. Thanks!
